name: salmon_quant
description: Generate counts using salmon pseudoalignment
tools:
  - salmon:
      homepage: https://combine-lab.github.io/salmon
      docs: https://combine-lab.github.io/salmon
input:
  - sample:
      type: val 
      decsription: Sample identifier
  - reads:
      type: path
      decsription: Input fastq files, read 1 and read 2
output:
  - quant.sf:
      type: path 
      decsription: Plain text tsv containing quantification data for the sample
  - cmd_info.json:
      type: path 
      decsription: json file with the command line parameters used
  - aux_info:
      type: path 
      decsription: Directory containg additional info about the salmon run        
authors: 
  - "@samleenz"
